# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ceacbaa15c7f9222bebac7a31380fc630004ee908bbeca4dddd5d9b253b44b05df95845505cd0e65ed921097dcdbf20414c133bd6b1a0387220588dde725e59

test:
  secret_key_base: 0988d371afe60bf9a7e686ab165a60f8a3ff9bfedf2d9c1e070a90fe5a8cb0d52a8870ee67219a8f0d91154c037b0d943eb1841c053f81401f51ee4715ed65fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
